itree_test: ../obj/ITreeNodeTest.o ../obj/ITreeNode.o
	g++ ../obj/ITreeNodeTest.o ../obj/ITreeNode.o -o itree_test

../obj/ITreeNodeTest.o: ITreeNodeTest.cpp
	g++ -c ITreeNodeTest.cpp -o ../obj/ITreeNodeTest.o

../obj/ITreeNode.o:../src/ITreeNode.cpp ../src/ITreeNode.h
	g++ -c ../src/ITreeNode.cpp -o ../obj/ITreeNode.o
